### ISSUE TITLE
Add frFR support

### ISSUE THREAD

**Issue by KatyPurry** [teelolws/WhereTheZaralek#1]
Hello,
I don't know if iot's because I'm using a non English client, but I don't have any sound alert nor arrow on my map. Addon is enabled, sound set. I'm using 10.1-002 version.

thank you

**Comment by teelolws** [comment]
Hi,
If you want this to work in non-English clients, I will need a list of the phrases that are announced to the zone in your language. You can see the English phrases at https://wowpedia.fandom.com/wiki/Zaralek_Cavern such as:

> Imperfect Balance [35.5, 51.3] - A vicious roar resonates through the caldera.
> Mortar Warfare [40.6, 43.1] - War cries erupt from the caldera as the djaradin begin to assemble their ballistae.
> Seismic Ceremony [34.5, 48.2] - The caldera begins to rumble...

**Comment by KatyPurry** [comment]
Hello, 
Thank you for your reply !
Do you need event names as well ?

**Comment by teelolws** [comment]
I will need to know which event the phrase is for, or the (approximate) coordinates. I don't need the name of the event in your language.

**Comment by KatyPurry** [comment]
Okay, I'll try to post the sentences I discover as I go along, it might take a few days/weeks.

Update : 



|Coords|Name|Syntax|
|-----------|-----------|-----------|
|57.7, 56.2 | Smelly Scramble |  Muskran l’Odoramancien se prépare à passer à l’action ! |
|57.3, 49.7 | Shellfire  | Un élémentaire de feu approche d’Olfor et de la grosse Bessie ! |
|44.41, 74.52|Cascade Calling*|Vous sentez la température dans les grottes augmenter considérablement.|
|63.3, 47.6|Crystalline Survey|Le bruit des cristaux résonne dans toute la caverne. L’analyse géologique va commencer près du Passage ! |
|40.6, 43.1|Mortar Warfare|Des cris de guerre fusent de la caldeira, alors que les troupes djaradines commencent à assembler leurs balistes.|
|60.7, 53.8|Smellincense|Delvert commence à faire chauffer sa marmite odorante près du lac des Abysses !|
|58.1, 66.9|Whirling Zephyr|L’atmosphère vrombit d’énergie tandis que les Primalistes invoquent une tempête !|
|40.6, 43.1|Mortar Warfare|Des cris de guerre fusent de la caldeira, alors que les troupes djaradines commencent à assembler leurs balistes. |


*I didn't found the event on the wowpedia page.

**Comment by teelolws** [comment]
Is that frFR?

**Comment by teelolws** [comment]
So I can give you the contribution credit you deserve, please make an edit in this PR, even if you just add a space or something: https://github.com/teelolws/WhereTheZaralek/pull/2

**Comment by teelolws** [comment]
Doing some testing with my game client in french. There is some kind of special character just before the `!` on some of the lines.

**Comment by KatyPurry** [comment]
Oh, I was tired, yes it's for the French loc ! :D 

Weird for the special character, I copy/paste from the game thanks to ElvUI. I'll rewrite by hand if not!

**Comment by teelolws** [comment]
Thats okay, I think Github changed the special character but I fixed it.
