### ISSUE TITLE
Maybe alert for rare mobs also?

### ISSUE THREAD

**Issue by arcadepro** [teelolws/WhereTheZaralek#4]
Perhaps add a sound/taskbar flash for rare mobs too. I mistakenly believed this was also the point of the addon rather than just waypoint the quest-like events.

**Comment by teelolws** [comment]
Hi, the addon isn't designed for rare spawns as they're covered by other addons already (SilverDragon, RareScanner, etc). This one is for finding the little events when they're announced, as the game doesn't plot anything on your map to indicate where it is, if you're not already close to it!

**Comment by teelolws** [comment]
Another author helped me implement Rare support today. You'll need to go into Interface options to turn it on.

Implemented in: https://github.com/teelolws/WhereTheZaralek/commit/026633224965c07add36e3afd7b0002e4d1a6bcf
