### ISSUE TITLE
Ru client strings

### ISSUE THREAD

**Issue by Ranlom874** [teelolws/WhereTheZaralek#8]
Hello, thx for your work!
Attached are some translations for RU WoW client

[RU_zara_events.xlsx](https://github.com/teelolws/WhereTheZaralek/files/11432386/RU_zara_events.xlsx)

**Comment by teelolws** [comment]
Can you confirm that I should be using `…` instead of `...`? They're not the same - it needs to be exact to text match!

**Comment by teelolws** [comment]
Theres no announcement for it, unfortunately, but need a name for Monument Maintenance so it shows in the list:
![image](https://github.com/teelolws/WhereTheZaralek/assets/49792789/d1ae50d1-b330-427c-894f-1d28f484beef)
https://github.com/teelolws/WhereTheZaralek/commit/25963ff21be31e0e55fbf76ce6789ea6be9a13a6

**Comment by Ranlom874** [comment]
> 

well, I'm not able to copy the exact symbol from chat emote, but I believe that ... is same for all languages

Monumental maintenance will be Ремонт монумента
Stress express - Стресс экспресс
Aberrus - Аберрус
Snail daily and Daily snail both can be translated as Дейлик улиток
and there is a typo in Seismic Ceremony - it is Сейсмическая not Сейсмическяа (my bad, sorry)
