### ISSUE TITLE
Any way to Make the list scaleable?

### ISSUE THREAD

**Issue by HeadMistressSydonie** [teelolws/WhereTheZaralek#9]
Hi! I love this addon but  i would love to be able to scale the words to make it fit the perimeter of my screen .. is that possible? Also for notification sounds I was so bummed to not hear the succubus whip moan noise! Keep up the great work!

**Comment by teelolws** [comment]
For the resize - you can resize it during edit mode:
![image](https://github.com/teelolws/WhereTheZaralek/assets/49792789/4bd63762-ca08-4e20-a199-8273da70fcda)

For the sound, you can add the option with:
`/run LibStub("LibSharedMedia-3.0"):Register("sound", "Succubus Whip", 1466150)`

That probably won't persist through a login. You'll need to find something that can run it every login / reload.

**Comment by Quartzfire** [comment]
Please add this information to the addon description main page on curse or something. I almost deleted the addon because I couldn't figure out how to move it - and luckily came here and saw this information.

**Comment by teelolws** [comment]
Yeah ok.
